//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDatabaseEntities : DbContext
    {
        public LibraryDatabaseEntities()
            : base("name=LibraryDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<BookTable> BookTables { get; set; }
        public virtual DbSet<BorrowerTable> BorrowerTables { get; set; }
        public virtual DbSet<LibraryStaff> LibraryStaffs { get; set; }
        public virtual DbSet<Patron> Patrons { get; set; }
        public virtual DbSet<SystemTable> SystemTables { get; set; }
        public virtual DbSet<TransactionTable> TransactionTables { get; set; }
    }
}
